### ISSUE TITLE
Demo exiting with fatal error

### ISSUE THREAD

**Issue by Clint67** [amrfarid140/webrtc-android-codelab#1]
Hi ,
I've tryed your demo from master branch as your istructions.
I got the server running
I got the app installed on two android device (both with android 6).
Immediately after run the app, I got the fatal error.
I tryed debuging the app and I got the error in the 'class SignallingClient', function Connect (after the debug exits from 'client' initialization).
The exception occours before the server get any request...

**Comment by Clint67** [comment]
This is the callstack I got from Android studio console

E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: me.amryousef.webrtc_demo, PID: 32027
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at io.ktor.util.Base64JvmKt.encodeBase64(Base64Jvm.kt:15)
        at io.ktor.client.features.websocket.WebSocketContent.<init>(WebSocketContent.kt:17)
        at io.ktor.client.features.websocket.WebSockets$Feature$install$1.invokeSuspend(WebSockets.kt:37)
        at io.ktor.client.features.websocket.WebSockets$Feature$install$1.invoke(WebSockets.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:278)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:63)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:137)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:157)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:23)
        at io.ktor.client.HttpClient.execute(HttpClient.kt:152)
        at io.ktor.client.call.HttpClientCallKt.call(HttpClientCall.kt:80)
        at io.ktor.client.call.UtilsKt.call(utils.kt:16)
        at io.ktor.client.features.websocket.BuildersKt.webSocketRawSession(builders.kt:105)
        at io.ktor.client.features.websocket.BuildersKt.webSocketSession(builders.kt:25)
        at io.ktor.client.features.websocket.BuildersKt.webSocket(builders.kt:59)
        at io.ktor.client.features.websocket.BuildersKt.ws(builders.kt:92)
        at io.ktor.client.features.websocket.BuildersKt.ws$default(builders.kt:91)
        at me.amryousef.webrtc_demo.SignallingClient$connect$1.invokeSuspend(SignallingClient.kt:57)

**Comment by Clint67** [comment]
It seems the problem is on Android device. At least for Android 6.
I run the same code on Android Pie and it got connected to the server without problem.

**Comment by Clint67** [comment]
It seems also Ktor team just released versione 1.2.3 that remove java.utils imports that cause the problem in older android version...
