### ISSUE TITLE
Mobile App Crashing - Error : java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;

### ISSUE THREAD

**Issue by sajidjutt7** [amrfarid140/webrtc-android-codelab#5]
Server is running and is responding at http://0.0.0.0:8080

Now to open mobile app. you mentioned this and i followed

Open mobile in Android Studio, then navigate to SignallingClient. You find HOST_ADDRESS, change its value with your local IP address.

On opening mobile in Android Studio. AS made 2 changes to mobile project
1. Change gradle version as:
-        classpath 'com.android.tools.build:gradle:3.5.0-beta03'
+        classpath 'com.android.tools.build:gradle:3.5.3'
2. Change SDK dir as:
-sdk.dir=/Users/amryousef/Library/Android/sdk
+sdk.dir=/Users/myName/Library/Android/sdk

I have tried HOST_ADDRESS with all the options. It is giving same error (I am pasting logs below).
These options i have tested individually:
private const val HOST_ADDRESS = "192.168.0.12"
private const val HOST_ADDRESS = "0.0.0.0"
private const val HOST_ADDRESS = "0.0.0.0:8080"
private const val HOST_ADDRESS = "My Local ip address"
Nothing is working. Same crash and logs

Pasting logs here. Please suggest what should i do to make it working. server is running. and mobile app is crashing. Thanks

`
2020-03-06 17:33:27.846 28327-28375/me.amryousef.webrtc_demo E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: me.amryousef.webrtc_demo, PID: 28327
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at io.ktor.util.Base64JvmKt.encodeBase64(Base64Jvm.kt:15)
        at io.ktor.client.features.websocket.WebSocketContent.<init>(WebSocketContent.kt:17)
        at io.ktor.client.features.websocket.WebSockets$Feature$install$1.invokeSuspend(WebSockets.kt:37)
        at io.ktor.client.features.websocket.WebSockets$Feature$install$1.invoke(WebSockets.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:278)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:63)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:137)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:157)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:23)
        at io.ktor.client.HttpClient.execute(HttpClient.kt:152)
        at io.ktor.client.call.HttpClientCallKt.call(HttpClientCall.kt:80)
        at io.ktor.client.call.UtilsKt.call(utils.kt:16)
        at io.ktor.client.features.websocket.BuildersKt.webSocketRawSession(builders.kt:105)
        at io.ktor.client.features.websocket.BuildersKt.webSocketSession(builders.kt:25)
        at io.ktor.client.features.websocket.BuildersKt.webSocket(builders.kt:59)
        at io.ktor.client.features.websocket.BuildersKt.ws(builders.kt:92)
        at io.ktor.client.features.websocket.BuildersKt.ws$default(builders.kt:91)
        at me.amryousef.webrtc_demo.SignallingClient$connect$1.invokeSuspend(SignallingClient.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/app/me.amryousef.webrtc_demo-1/base.apk"],nativeLibraryDirectories=[/data/app/me.amryousef.webrtc_demo-1/lib/x86, /data/app/me.amryousef.webrtc_demo-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.ktor.util.Base64JvmKt.encodeBase64(Base64Jvm.kt:15) 
        at io.ktor.client.features.websocket.WebSocketContent.<init>(WebSocketContent.kt:17) 
        at io.ktor.client.features.websocket.WebSockets$Feature$install$1.invokeSuspend(WebSockets.kt:37) 
        at io.ktor.client.features.websocket.WebSockets$Feature$install$1.invoke(WebSockets.kt) 
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:278) 
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:63) 
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:137) 
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:157) 
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:23) 
        at io.ktor.client.HttpClient.execute(HttpClient.kt:152) 
        at io.ktor.client.call.HttpClientCallKt.call(HttpClientCall.kt:80) 
        at io.ktor.client.call.UtilsKt.call(utils.kt:16) 
        at io.ktor.client.features.websocket.BuildersKt.webSocketRawSession(builders.kt:105) 
        at io.ktor.client.features.websocket.BuildersKt.webSocketSession(builders.kt:25) 
        at io.ktor.client.features.websocket.BuildersKt.webSocket(builders.kt:59) 
        at io.ktor.client.features.websocket.BuildersKt.ws(builders.kt:92) 
        at io.ktor.client.features.websocket.BuildersKt.ws$default(builders.kt:91) 
        at me.amryousef.webrtc_demo.SignallingClient$connect$1.invokeSuspend(SignallingClient.kt:58) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) `

**Comment by mhoyosga** [comment]
I have the same error.

Any idea???
